vocab_file: '../data_g2s/data_new/vocab.json'
data: '../data_g2s/data_new/'
batch_size: 256
vocab_size: 50004
type_num_sam: 5
type_num_gen: 3
head_num: 8
log: '../data_g2s/log/'
epoch: 15
optim: 'adam'
learning_rate: 0.001
learning_rate_sample: 0.0001
max_grad_norm: 8
learning_rate_decay: 0.5
schedule: True
start_decay_at: 1
emb_size: 128
encoder_hidden_size: 256
decoder_hidden_size: 256
num_layers: 3
bidirec: True
dropout: 0.1
max_tgt_len: 20
eval_interval: 8309
save_interval: 8309
metric: ['bleu', 'xent']
#shared_vocab: True
sample_num: 10
num_head: 8
dim_feedforward: 1024
use_wordtype: False
lr_t_max: 15
lr_decay_epoch: 0
lr_decay: 8039
lr_decay_min: 8039
KG_weight: '../data_g2s/data_new/KG_weight.json'
KG_data: '../data_g2s/data_new/graph_filt.json'
graph_model: 'gcn-lstm'  #[gcn-uni,gat-lstm,gcn-lstm,gcn-lstm-n,gcn-gat-lstm]
use_copy:  False
